The ``7-base-geometry`` module
==============================

The ``-7-base-geometry`` module defines a geometry class BaseGeometry

Usage
------

``BaseGeometry`` has no attributes and takes no arguments

::

	>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry
	>>> bg = BaseGeometry()
	>>> type(bg)
	<class '7-base_geometry.BaseGeometry'>

``BaseGeometry`` takes no arguments

::

	>>> bg = BaseGeometry("something here")
	Traceback (most recent call last):
		...
	TypeError: BaseGeometry() takes no arguments

Supplies two methods
- ``area(..)``
::

	>>> bg = BaseGeometry()
	>>> print(bg.area) # doctest: +ELLIPSIS, +NORMALIZE_WHITESPACE
	<bound method BaseGeometry.area of <7-base_geometry.BaseGeometry 
	object at...>>

``integer_validator(...)`` validates the type of ``value`` \
(should be 'int'), where ``name`` is the name.
::

	>>> bg = BaseGeometry()
	>>> bg.integer_validator("number", 2)

Returns error if ``value`` not int

::

	>>> bg.integer_validator("invalid", "invalid")
	Traceback (most recent call last):
		...
	TypeError: invalid must be an integer
	>>> bg.integer_validator("invalid number", True)
	Traceback (most recent call last):
		...
	TypeError: invalid number must be an integer
	>>> bg.integer_validator("invalid number", [1])
	Traceback (most recent call last):
		...
	TypeError: invalid number must be an integer
	>>> bg.integer_validator("invalid number", (1,))
	Traceback (most recent call last):
		...
	TypeError: invalid number must be an integer
	>>> bg.integer_validator("invalid number", None)
	Traceback (most recent call last):
		...
	TypeError: invalid number must be an integer
	>>> bg.integer_validator("invalid number", {2, 5})
	Traceback (most recent call last):
		...
	TypeError: invalid number must be an integer

``integer_validator(...)`` must be supplied two arguments

::
	>>> bg.integer_validator("one argument")
	Traceback (most recent call last):
		...	
	TypeError: integer_validator() missing 1 required positional argument: 'value'

	>>> bg.integer_validator({"a": 1}, (1, 2))
	Traceback (most recent call last):
		...
	TypeError: {'a': 1} must be an integer
